name: Build and Package

on:
  push:
    branches: [ main, release ]
  release:
    types: [ created ]

jobs:
  build-debian:
    runs-on: ubuntu
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
      
    - name: Set up Qt
      uses: jurplel/install-qt-action@v4.3.0
      with:
        qt-version: 6.9.0
        cmake: true
        cached: true
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake debhelper pkg-config
        sudo apt-get install -y libgl1-mesa-dev libxkbcommon-x11-dev
        
    - name: Configure and build
      run: |
        cmake -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
        cmake --build build --parallel
        
    - name: Install linuxdeployqt
      run: |
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x linuxdeployqt-continuous-x86_64.AppImage
        
    - name: Create AppDir
      run: |
        mkdir -p AppDir/usr/bin
        cp build/PasswordGenerator AppDir/usr/bin/
        cp PasswordGenerator.desktop AppDir/
        cp icons/icon.png AppDir/PasswordGenerator.png
        
    - name: Bundle dependencies
      run: |
        ./linuxdeployqt-continuous-x86_64.AppImage AppDir/usr/bin/PasswordGenerator -appimage
        ./linuxdeployqt-continuous-x86_64.AppImage AppDir/PasswordGenerator.desktop -appimage
        
    - name: Create Debian package
      run: |
        mkdir -p password-generator_1.1-1_amd64/usr/bin
        mkdir -p password-generator_1.1-1_amd64/usr/share/applications
        mkdir -p password-generator_1.1-1_amd64/usr/share/icons/hicolor/128x128/apps
        
        cp AppDir/usr/bin/PasswordGenerator password-generator_1.1-1_amd64/usr/bin/
        cp PasswordGenerator.desktop password-generator_1.1-1_amd64/usr/share/applications/
        cp icons/icon.png password-generator_1.1-1_amd64/usr/share/icons/hicolor/128x128/apps/PasswordGenerator.png
        
        mkdir -p password-generator_1.1-1_amd64/DEBIAN
        cat > password-generator_1.1-1_amd64/DEBIAN/control <<EOF
        Package: password-generator
        Version: 1.1-1
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: Security Team <security@example.com>
        Depends: libqt6core6 (>= 6.9.0), libqt6gui6 (>= 6.9.0), libqt6widgets6 (>= 6.9.0), libc6 (>= 2.31)
        Description: Secure password generator
         A Qt-based application for generating random passwords with options for
         letters, numbers, and special characters. Includes history tracking and
         password strength estimation.
        EOF
        
        dpkg-deb --build password-generator_1.1-1_amd64
        mv password-generator_1.1-1_amd64.deb PasswordGenerator_1.1_amd64.deb
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: PasswordGenerator_Debian
        path: |
          PasswordGenerator_1.1_amd64.deb
          PasswordGenerator-x86_64.AppImage
