name: Build and Package

on:
  push:
    branches: [ main, release ]
  release:
    types: [ created ]

jobs:
  build-debian:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: List files (debug)
      run: ls -la
      
    - name: Set up Qt
      uses: jurplel/install-qt-action@v4.3.0
      with:
        qt-version: 6.9.0
        cmake: true
        cached: true
        # 添加环境变量导出
        setup-python: true
        
    - name: Print Qt environment (debug)
      run: |
        echo "Qt6_DIR: $Qt6_DIR"
        echo "PATH: $PATH"
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake debhelper pkg-config
        sudo apt-get install -y libgl1-mesa-dev libxkbcommon-x11-dev
        
    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
        cmake --build . --parallel
        
    - name: Verify build
      run: |
        cd build
        ls -la
        file PasswordGenerator
        
    - name: Create Debian package
      run: |
        mkdir -p password-generator/usr/bin
        mkdir -p password-generator/usr/share/applications
        mkdir -p password-generator/usr/share/icons/hicolor/128x128/apps
        
        cp build/PasswordGenerator password-generator/usr/bin/
        cp PasswordGenerator.desktop password-generator/usr/share/applications/
        cp icons/icon.png password-generator/usr/share/icons/hicolor/128x128/apps/PasswordGenerator.png
        
        mkdir -p password-generator/DEBIAN
        cat > password-generator/DEBIAN/control <<EOF
        Package: password-generator
        Version: 1.1-1
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: Security Team <security@example.com>
        Depends: libqt6core6 (>= 6.9.0), libqt6gui6 (>= 6.9.0), libqt6widgets6 (>= 6.9.0), libc6 (>= 2.31)
        Description: Secure password generator
         A Qt-based application for generating random passwords with options for
         letters, numbers, and special characters. Includes history tracking and
         password strength estimation.
        EOF
        
        dpkg-deb --build password-generator
        mv password-generator.deb PasswordGenerator_1.1_amd64.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: PasswordGenerator_Debian
        path: |
          PasswordGenerator_1.1_amd64.deb
